/*
 * Copyright 2012 Thingtrack S.L.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.vaadin.addons.sliderlayout.layout;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class Detail extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Table tableDetail;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Detail() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		tableDetail.setImmediate(true);
		tableDetail.setSelectable(true);
		tableDetail.setMultiSelect(false);
		tableDetail.setNullSelectionAllowed(false);
		
		tableDetail.addContainerProperty("Product", String.class, null);
		tableDetail.addContainerProperty("Price", Float.class, null);
		
		// Add rows to the table
		Object newItem01 = tableDetail.addItem();
		Item row01 = tableDetail.getItem(newItem01);
		row01.getItemProperty("Product").setValue("Orange");
		row01.getItemProperty("Price").setValue(20f);

		Object newItem02 = tableDetail.addItem();
		Item row02 = tableDetail.getItem(newItem02);
		row02.getItemProperty("Product").setValue("Apple");
		row02.getItemProperty("Price").setValue(450f);	
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tableDetail
		tableDetail = new Table();
		tableDetail.setImmediate(false);
		tableDetail.setWidth("100.0%");
		tableDetail.setHeight("100.0%");
		mainLayout.addComponent(tableDetail);
		mainLayout.setExpandRatio(tableDetail, 1.0f);
		
		return mainLayout;
	}

}
