/*
 * Copyright 2012 Thingtrack S.L.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.vaadin.addons.sliderlayout.layout;

import java.util.Date;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class SubDetail01 extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private TabSheet tabSheet;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public SubDetail01() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		Table tableSubDetail = new Table();
		tableSubDetail.setSizeFull();
		tableSubDetail.setImmediate(true);
		tableSubDetail.setSelectable(true);
		tableSubDetail.setMultiSelect(false);
		tableSubDetail.setNullSelectionAllowed(false);
		
		tableSubDetail.addContainerProperty("Offer", String.class, null);
		tableSubDetail.addContainerProperty("Price", Float.class, null);
		tableSubDetail.addContainerProperty("Date", Date.class, null);
		
		// Add rows to the table
		Object newItem01 = tableSubDetail.addItem();
		Item row01 = tableSubDetail.getItem(newItem01);
		row01.getItemProperty("Offer").setValue("B34355");
		row01.getItemProperty("Price").setValue(20f);
		row01.getItemProperty("Date").setValue(new Date());

		Object newItem02 = tableSubDetail.addItem();
		Item row02 = tableSubDetail.getItem(newItem02);
		row02.getItemProperty("Offer").setValue("GH3535");
		row02.getItemProperty("Price").setValue(500f);
		row02.getItemProperty("Date").setValue(new Date());
		
		Object newItem03 = tableSubDetail.addItem();
		Item row03 = tableSubDetail.getItem(newItem03);
		row03.getItemProperty("Offer").setValue("JU8888");
		row03.getItemProperty("Price").setValue(10f);
		row03.getItemProperty("Date").setValue(new Date());
		
		tabSheet.addTab(tableSubDetail, "Offers");
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tabSheet
		tabSheet = new TabSheet();
		tabSheet.setImmediate(false);
		tabSheet.setWidth("100.0%");
		tabSheet.setHeight("100.0%");
		mainLayout.addComponent(tabSheet);
		mainLayout.setExpandRatio(tabSheet, 1.0f);
		
		return mainLayout;
	}

}
